name: Hola Mundo

##on: [push]

#Evento que se dispara cuando se hace un push a la rama main, también aplica para pull_request
on:
  push:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

      - name: touch file
        run: touch file.txt

      - name: set text
        run: echo "Hola mundo" >> file.txt

      - name: read file
        run: cat file.txt

  other:
    runs-on: ubuntu-latest

    #Agregar secuencia de ejecución de jobs.
    needs: [Hola]
    steps:
      - name: LS
        run: ls -al

  paquete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Paquete
        run: |
          chmod +x script.sh
          ./script.sh
